version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    platform: linux/arm64/v8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin service
  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: laravel-php
    platform: linux/arm64/v8
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  mysql_data:
